# 1. Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/tapir_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Xi&EwtLBXTxqXgzr%ho$2owMM#C6tqWxsbnnB!hpkr#v!Bx%a5n66kix4HYCDt#MZGA%qEup@Q2eSGcQfqEL@rkBq*Uxc2%AJGL9
# ^^^ CHANGE THIS TO THE PASSWORD YOU SET IN THE INSTALLER!

# 2. JPA / Hibernate Settings
# 'update': keeps your data but updates the schema if you change Java code.
# 'validate': checks if Java matches MySQL perfectly.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false